### ISSUE TITLE
Update project list with new projects

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/code-for-miami.github.io_v1#17]
- Local Business Tax data API
- StateDecoded
- Open 311 Efforts? ( @rebekahmonson do you have opinions about that?)

**Comment by rebekahmonson** [comment]
Nope. Will dump new data this weekend. Would be good to start messing around with it.

**Comment by rebekahmonson** [comment]
All fixed. Will add 311 over weekend.
