### ISSUE TITLE
Need to add Code for America widget

### ISSUE THREAD

**Issue by antoniorllanos** [CodeforSouth/code-for-miami.github.io_v1#21]
The following needs to be added, it allows for us to display tasks that we need help with on our projects. Probably under our project list.

<iframe src="http://codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Miami&number=12" width="100%" height="600" frameBorder="0"></iframe>

**Comment by aramonc** [comment]
This is the code that needs to be added.

@ErnieAtLYD @CristinaSolana & other designers, where would be a good place to put this?

``` html
<iframe src="http://codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Miami&number=6" width="100%" height="600" frameBorder="0"></iframe>
```

**Comment by CristinaSolana** [comment]
Pardon my ignorance, what does this do?

**Comment by aramonc** [comment]
@CristinaSolana basically this http://www.codeforamerica.org/geeks/civicissues

**Comment by CristinaSolana** [comment]
@aramonc @ernieatlyd Oh, I see, the original issue didn't come through via email. Dope. @rebekahmonson and I briefly touched on the idea of redesigning the site. Maybe we should plan on a redesign milestone and include this in that milestone?

**Comment by aramonc** [comment]
@CristinaSolana wouldn't be a bad idea. I've been thinking we may want to start setting more milestones & I know @antoniorllanos will probably agree that using more issues to track things will help a lot :D

cc: @ErnieAtLYD @rebekahmonson

**Comment by antoniorllanos** [comment]
I think one of the main reasons for this is to publicize on our site where we need help.  I am starting to notice duplication of efforts in a lot of areas where 2 people are doing the same thing.  With the widget, the idea is that what we need help with is advertised on our site.  We can add tags like "beginner", or "PHP" for people to see and take.  Just noticed in the State Decoded that someone else is trying to develop a skin for the site. This lets us focus the casual member to see what they can do to help out.

**Comment by aramonc** [comment]
+1 to what @antoniorllanos said :)

**Comment by CristinaSolana** [comment]
@antoniorllanos @aramonc, In the meantime, we can place the widget in place of: 

![screen shot 2014-09-04 at 3 54 31 pm](https://cloud.githubusercontent.com/assets/524896/4156030/1bc0202e-3470-11e4-8127-2f27eb20e560.png)

**Comment by antoniorllanos** [comment]
I was thinking of actually just adding it below it.

**Comment by ErnieAtLYD** [comment]
Okay - I'll create a new issue specifically addressing the redesign. You'll want to see the link I post there.
