### ISSUE TITLE
Fix top margin on Laddr CSS to work with CfM Top menu

### ISSUE THREAD

**Issue by aramonc** [CodeforSouth/code-for-miami.github.io_v1#22]
This happens after updating a project or doing anything on the profile page

![2014-09-03-223439_3360x1050_scrot](https://cloud.githubusercontent.com/assets/2242224/4144415/cd188c30-33df-11e4-9d8e-6fc53d0965c8.png)

**Comment by ErnieAtLYD** [comment]
This may be a laddr thing. I filed a bug on their side and I'll have Chris from Philly look at it.
https://github.com/CfABrigadePhiladelphia/laddr/issues/35

**Comment by CristinaSolana** [comment]
Done.
