### ISSUE TITLE
Consider codeformiami.org re-design using codeforsanfrancisco.org's base

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/code-for-miami.github.io_v1#23]
The new version of Code for SF's website embeds the new widget:
http://codeforsanfrancisco.org/

Their github repo is here:
https://github.com/sfbrigade/sfbrigade.github.io

**Comment by ErnieAtLYD** [comment]
pinging @antoniorllanos @aramonc @CristinaSolana @rebekahmonson

**Comment by ondrae** [comment]
I'll be writing up our plan for Code for San Francisco site soonish. I want it to be useful for any new Brigade when they are just getting started. It will be powered by the [CfAPI](https://github.com/codeforamerica/cfapi) and easy to configure.

I found this Issue via the [Civic Tech Issue Finder](http://www.codeforamerica.org/geeks/civicissues/embed)
