### ISSUE TITLE
Shouldn't we get rid of the GitHub banner?

### ISSUE THREAD

**Issue by TheGhostHorse** [CodeforSouth/code-for-miami.github.io_v1#24]
I have found that the GitHub banner overlaps the English/Español button depending on the width of the browser's window preventing users from switching between the English and Spanish versions of the website (If the issue is not obvious to you, try resizing your browser). So, Wouldn't it be better to just get rid of the GitHub banner altogether?

**Comment by aramonc** [comment]
I think a better solution would be to move the banner. There's different banner for each corner, so it doesn't have to stay where it is now. 

If there is no better place to put it because it would cause similar issues, then maybe moving the language link to a place that's more obvious would work as well.

**Comment by TheGhostHorse** [comment]
I will play around with the media queries to see if I can make it fit better.

**Comment by ErnieAtLYD** [comment]
I'm also okay with removing the lightbulb icon in the lower right hand corner (no one uses it, alas) OR moving the language links right next to the nav bar too. Just upload a screenshot so we can see how it looks!

**Comment by aramonc** [comment]
Woah! I didn't even know that was there! cool idea though :)

**Comment by TheGhostHorse** [comment]
I removed the light bulb icon in the lower right hand corner, but it is very difficult to make the GitHub banner and the language link stay away from each other through the media queries because 1) The navigation bar was made with a fixed width, and 2) Since the website uses bootstrap, the main CSS file is at http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css and is compressed.

So, the options I see are:
1) Stop using bootstrap and create our own CSS, which would basically mean a redesign of the page.
OR
2) Remove the GitHub banner because I don't see where we could place it without it interfering with something.

Tell me if you want me to submit the version without the light bulb.

**Comment by ErnieAtLYD** [comment]
Adrian, let's do #2 for now.

I think down the line we'll want to redesign the page anyway. A possible
contender I'm looking at is a simpler, cleaner version based on Code for
San Francisco: http://codeforsanfrancisco.org/
- E
