### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by rebekahmonson** [CodeforSouth/code-for-miami.github.io_v1#3]
Let's get this translated into Spanish and Creole too.

**Comment by aramonc** [comment]
How can we handle this? Can we have subdomains? Different html file for each language?

Being a PHP dev I only know how to do this using PHP to detect location codes on the URL or on the HTTP request.

**Comment by ErnieAtLYD** [comment]
You could definitely clone two of the same repo and point those to
subdomains like es.codeformiami.org and ht.codeformiami.org for Kreyol.
More information here:
https://help.github.com/articles/setting-up-a-custom-domain-with-pages

**Comment by virgiliud** [comment]
If needed I can create a choose language dropdown in the site menu with links to the subdomains.

**Comment by ErnieAtLYD** [comment]
@virgiliud - now that we have es.codeformiami.org, would you like to implement this?

**Comment by virgiliud** [comment]
@ErnieAtLYD OK! I'll implement it. Thanks.

**Comment by ErnieAtLYD** [comment]
Todos, buen trabajo!
