### ISSUE TITLE
Iam1of.us link does not redirect correctly

### ISSUE THREAD

**Issue by mugabits** [CodeforSouth/code-for-miami.github.io_v1#30]
When you click the demo link for Iam1of.us, it redirects to  http://codeformiami.org/iam1of.us instead of iam1of.us

See the picture below: 
<img width="226" alt="screen shot 2015-09-01 at 10 04 08 pm" src="https://cloud.githubusercontent.com/assets/8159215/9621562/ffc678f2-50f5-11e5-9a32-a6d0cb2d61b2.png">

Environment:
MAC OS X Yosemite Version 10.10.5
Google Chrome Version 43.0.2357.130 (64-bit)

**Comment by CristinaSolana** [comment]
Iam1ofus is an archived project so there is no demo or code available for viewing.
This is the projects page: http://codefor.miami/projects. The old projects site is not in use.
