### ISSUE TITLE
Check the Meetup APIKey 

### ISSUE THREAD

**Issue by rebekahmonson** [CodeforSouth/code-for-miami.github.io_v1#4]
Looks like some of the JS to display checkins still points at Code for Hampton Roads.

**Comment by antoniorllanos** [comment]
Do you have the Code for Miami Key?

**Comment by rebekahmonson** [comment]
Haven't worked with Meetup API before, so was planning to do some reading this weekend. http://www.meetup.com/meetup_api/

**Comment by antoniorllanos** [comment]
I'll knock it out tonight.. Since I don't administer the Meetup group, the admin needs to get this key, which may be visible under some admin screen.

**Comment by rebekahmonson** [comment]
Tagged Ernie to get you the key.

**Comment by ErnieAtLYD** [comment]
Hey Antonio,

Can you try the following key - I pulled this from my MeetUp page:
2975b6e4c43147824522959761677

Holler if this doesn't work for you. Thanks,
- Ernie

**Comment by ErnieAtLYD** [comment]
Antonio put this in the code, I just never closed the bug, that's all. Nice job, Antonio!
