### ISSUE TITLE
Demo link for iam1of.us is dead

### ISSUE THREAD

**Issue by robinbijlani** [CodeforSouth/code-for-miami.github.io_v1#6]
The demo link for iam1of.us is dead in the nav and the Works in Progress section.

**Comment by ErnieAtLYD** [comment]
Oof. Christina, you were able to get the DNS/domain issues straightened out
for legislature tracker. Any idea why the URL won't resolve for this repo?

-E

**Comment by rebekahmonson** [comment]
He's talking about the link on the site, I think. Iam1of.us was working
last night.

-r

## rebekahmonson.com

Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by robinbijlani** [comment]
I'm referring to the links that point to http://code-for-miami.github.io/iam1of.us, which throws a Github Pages 404.

**Comment by ErnieAtLYD** [comment]
It's some weird Github DNS caching thing I think, It happens pretty
regularly, they end up having to "rebuild". I opened a ticket. Should be
fixed by tomorrow based on past experience.

Cheers,

Cristina Solana
http://github.com/cristinasolana
http://dribbble.com/cristina.solana

**Comment by ErnieAtLYD** [comment]
They were faster than I expected. :)

---------- Forwarded message ----------
From: James Dennes support@github.com
Date: Tue, Sep 10, 2013 at 10:27 AM
Subject: Re: Project page 404: http://code-for-miami.github.io/iam1of.us
To: cs@nightshiftcreative.com

Hey Cristina,

Sorry for the trouble. I've just triggered a rebuild of that page, and it's
available again:

http://codeformiami.org/iam1of.us/

Let us know if there's any other trouble and we'll take a look.

Cheers,
James

Cheers,

Cristina Solana
http://github.com/cristinasolana
http://dribbble.com/cristina.solana

On Tue, Sep 10, 2013 at 10:27 AM, Cristina Solana <cs@nightshiftcreative.com

> wrote:
> 
> It's some weird Github DNS caching thing I think, It happens pretty
> regularly, they end up having to "rebuild". I opened a ticket. Should be
> fixed by tomorrow based on past experience.
> 
> Cheers,
> 
> Cristina Solana
> http://github.com/cristinasolana
> http://dribbble.com/cristina.solana
> 
> On Tue, Sep 10, 2013 at 9:50 AM, Ernie Hsiung <

**Comment by robinbijlani** [comment]
Nice! :)
